---
- hosts: all
  vars:
    username: vagrant
  tasks:
    - include: ./tasks/base.yml
    - include: ./tasks/git.yml
    - include: ./tasks/nodejs_0.10.yml
    #- include: ./tasks/nodejs_0.12.yml
    #- include: ./tasks/iojs_1.x.yml
    #- include: ./tasks/iojs_2.x.yml
    - include: ./tasks/nvm.yml
    - include: ./tasks/vim-node-ide.yml
    - include: ./tasks/vim-theme-atom-dark.yml
    - include: ./tasks/vimx.yml
    - include: ./tasks/atom.yml
    - include: ./tasks/atom-packages-generic.yml
    - include: ./tasks/atom-packages-nodejs.yml
    - include: ./tasks/atom-packages-web.yml
    - include: ./tasks/sublime3.yml
    - include: ./tasks/kupfer.yml
    - include: ./tasks/leafpad.yml
    - include: ./tasks/google-chrome.yml

